/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TopicId = IDL.Nat;
export const QuizId = IDL.Nat;
export const QuizStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const QuestionId = IDL.Nat;
export const Quiz = IDL.Record({
  'id' : QuizId,
  'status' : QuizStatus,
  'createdAt' : Timestamp,
  'questionIds' : IDL.Vec(QuestionId),
  'topicId' : TopicId,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'source' : IDL.Variant({ 'manual' : IDL.Null, 'aiGenerated' : IDL.Null }),
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'isFlagged' : IDL.Bool,
  'topicId' : TopicId,
});
export const CaseId = IDL.Nat;
export const SubjectId = IDL.Nat;
export const DifficultyLevel = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const CaseQuestion = IDL.Record({
  'text' : IDL.Text,
  'modelAnswer' : IDL.Text,
});
export const EceCase = IDL.Record({
  'id' : CaseId,
  'title' : IDL.Text,
  'subjectTags' : IDL.Vec(SubjectId),
  'difficulty' : DifficultyLevel,
  'learningPoints' : IDL.Vec(IDL.Text),
  'questions' : IDL.Vec(CaseQuestion),
  'presentation' : IDL.Text,
});
export const FlashcardId = IDL.Nat;
export const Flashcard = IDL.Record({
  'id' : FlashcardId,
  'front' : IDL.Text,
  'back' : IDL.Text,
  'topicId' : TopicId,
});
export const QuizAttempt = IDL.Record({
  'completedAt' : Timestamp,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'quizId' : QuizId,
});
export const QuizResult = IDL.Record({
  'completedAt' : Timestamp,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Vec(IDL.Bool),
  'quizId' : QuizId,
  'percentage' : IDL.Float64,
});
export const SubjectName = IDL.Variant({
  'physiology' : IDL.Null,
  'anatomy' : IDL.Null,
  'biochemistry' : IDL.Null,
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'topicCount' : IDL.Nat,
  'name' : SubjectName,
  'description' : IDL.Text,
});
export const Topic = IDL.Record({
  'id' : TopicId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : SubjectId,
  'orderIndex' : IDL.Nat,
});
export const SubjectProgress = IDL.Record({
  'topicsStudied' : IDL.Nat,
  'masteryPercent' : IDL.Float64,
  'totalStudyMinutes' : IDL.Nat,
  'quizzesTaken' : IDL.Nat,
  'subjectId' : SubjectId,
  'flashcardsReviewed' : IDL.Nat,
});
export const UserProgress = IDL.Record({
  'streakDays' : IDL.Nat,
  'lastStudyDate' : IDL.Opt(Timestamp),
  'totalStudyMinutes' : IDL.Nat,
  'subjectProgress' : IDL.Vec(SubjectProgress),
});
export const ReviewRating = IDL.Variant({
  'easy' : IDL.Null,
  'good' : IDL.Null,
  'hard' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createQuiz' : IDL.Func([TopicId, IDL.Nat], [Quiz], []),
  'generateQuestionsForTopic' : IDL.Func([TopicId], [IDL.Vec(Question)], []),
  'getCase' : IDL.Func([CaseId], [IDL.Opt(EceCase)], ['query']),
  'getCases' : IDL.Func([IDL.Opt(SubjectId)], [IDL.Vec(EceCase)], ['query']),
  'getDueFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
  'getFlashcards' : IDL.Func([TopicId], [IDL.Vec(Flashcard)], ['query']),
  'getQuestion' : IDL.Func([QuestionId], [IDL.Opt(Question)], ['query']),
  'getQuestions' : IDL.Func([TopicId], [IDL.Vec(Question)], ['query']),
  'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getQuizResult' : IDL.Func([QuizId], [IDL.Opt(QuizResult)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTopic' : IDL.Func([TopicId], [IDL.Opt(Topic)], ['query']),
  'getTopics' : IDL.Func([SubjectId], [IDL.Vec(Topic)], ['query']),
  'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
  'markQuestionFlagged' : IDL.Func([QuestionId], [], []),
  'recordStudySession' : IDL.Func([SubjectId, IDL.Nat], [], []),
  'reviewFlashcard' : IDL.Func([FlashcardId, ReviewRating], [], []),
  'submitCaseAnswer' : IDL.Func([CaseId, IDL.Nat, IDL.Text], [], []),
  'submitQuiz' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [QuizResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TopicId = IDL.Nat;
  const QuizId = IDL.Nat;
  const QuizStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const QuestionId = IDL.Nat;
  const Quiz = IDL.Record({
    'id' : QuizId,
    'status' : QuizStatus,
    'createdAt' : Timestamp,
    'questionIds' : IDL.Vec(QuestionId),
    'topicId' : TopicId,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'source' : IDL.Variant({ 'manual' : IDL.Null, 'aiGenerated' : IDL.Null }),
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'isFlagged' : IDL.Bool,
    'topicId' : TopicId,
  });
  const CaseId = IDL.Nat;
  const SubjectId = IDL.Nat;
  const DifficultyLevel = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CaseQuestion = IDL.Record({
    'text' : IDL.Text,
    'modelAnswer' : IDL.Text,
  });
  const EceCase = IDL.Record({
    'id' : CaseId,
    'title' : IDL.Text,
    'subjectTags' : IDL.Vec(SubjectId),
    'difficulty' : DifficultyLevel,
    'learningPoints' : IDL.Vec(IDL.Text),
    'questions' : IDL.Vec(CaseQuestion),
    'presentation' : IDL.Text,
  });
  const FlashcardId = IDL.Nat;
  const Flashcard = IDL.Record({
    'id' : FlashcardId,
    'front' : IDL.Text,
    'back' : IDL.Text,
    'topicId' : TopicId,
  });
  const QuizAttempt = IDL.Record({
    'completedAt' : Timestamp,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'quizId' : QuizId,
  });
  const QuizResult = IDL.Record({
    'completedAt' : Timestamp,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Vec(IDL.Bool),
    'quizId' : QuizId,
    'percentage' : IDL.Float64,
  });
  const SubjectName = IDL.Variant({
    'physiology' : IDL.Null,
    'anatomy' : IDL.Null,
    'biochemistry' : IDL.Null,
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'topicCount' : IDL.Nat,
    'name' : SubjectName,
    'description' : IDL.Text,
  });
  const Topic = IDL.Record({
    'id' : TopicId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : SubjectId,
    'orderIndex' : IDL.Nat,
  });
  const SubjectProgress = IDL.Record({
    'topicsStudied' : IDL.Nat,
    'masteryPercent' : IDL.Float64,
    'totalStudyMinutes' : IDL.Nat,
    'quizzesTaken' : IDL.Nat,
    'subjectId' : SubjectId,
    'flashcardsReviewed' : IDL.Nat,
  });
  const UserProgress = IDL.Record({
    'streakDays' : IDL.Nat,
    'lastStudyDate' : IDL.Opt(Timestamp),
    'totalStudyMinutes' : IDL.Nat,
    'subjectProgress' : IDL.Vec(SubjectProgress),
  });
  const ReviewRating = IDL.Variant({
    'easy' : IDL.Null,
    'good' : IDL.Null,
    'hard' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createQuiz' : IDL.Func([TopicId, IDL.Nat], [Quiz], []),
    'generateQuestionsForTopic' : IDL.Func([TopicId], [IDL.Vec(Question)], []),
    'getCase' : IDL.Func([CaseId], [IDL.Opt(EceCase)], ['query']),
    'getCases' : IDL.Func([IDL.Opt(SubjectId)], [IDL.Vec(EceCase)], ['query']),
    'getDueFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
    'getFlashcards' : IDL.Func([TopicId], [IDL.Vec(Flashcard)], ['query']),
    'getQuestion' : IDL.Func([QuestionId], [IDL.Opt(Question)], ['query']),
    'getQuestions' : IDL.Func([TopicId], [IDL.Vec(Question)], ['query']),
    'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getQuizResult' : IDL.Func([QuizId], [IDL.Opt(QuizResult)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTopic' : IDL.Func([TopicId], [IDL.Opt(Topic)], ['query']),
    'getTopics' : IDL.Func([SubjectId], [IDL.Vec(Topic)], ['query']),
    'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
    'markQuestionFlagged' : IDL.Func([QuestionId], [], []),
    'recordStudySession' : IDL.Func([SubjectId, IDL.Nat], [], []),
    'reviewFlashcard' : IDL.Func([FlashcardId, ReviewRating], [], []),
    'submitCaseAnswer' : IDL.Func([CaseId, IDL.Nat, IDL.Text], [], []),
    'submitQuiz' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [QuizResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };