/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseId = bigint;
export interface CaseQuestion { 'text' : string, 'modelAnswer' : string }
export type DifficultyLevel = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface EceCase {
  'id' : CaseId,
  'title' : string,
  'subjectTags' : Array<SubjectId>,
  'difficulty' : DifficultyLevel,
  'learningPoints' : Array<string>,
  'questions' : Array<CaseQuestion>,
  'presentation' : string,
}
export interface Flashcard {
  'id' : FlashcardId,
  'front' : string,
  'back' : string,
  'topicId' : TopicId,
}
export type FlashcardId = bigint;
export interface Question {
  'id' : QuestionId,
  'source' : { 'manual' : null } |
    { 'aiGenerated' : null },
  'correctIndex' : bigint,
  'explanation' : string,
  'text' : string,
  'options' : Array<string>,
  'isFlagged' : boolean,
  'topicId' : TopicId,
}
export type QuestionId = bigint;
export interface Quiz {
  'id' : QuizId,
  'status' : QuizStatus,
  'createdAt' : Timestamp,
  'questionIds' : Array<QuestionId>,
  'topicId' : TopicId,
}
export interface QuizAttempt {
  'completedAt' : Timestamp,
  'answers' : Array<bigint>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'quizId' : QuizId,
}
export type QuizId = bigint;
export interface QuizResult {
  'completedAt' : Timestamp,
  'score' : bigint,
  'totalQuestions' : bigint,
  'correctAnswers' : Array<boolean>,
  'quizId' : QuizId,
  'percentage' : number,
}
export type QuizStatus = { 'active' : null } |
  { 'completed' : null };
export type ReviewRating = { 'easy' : null } |
  { 'good' : null } |
  { 'hard' : null };
export interface Subject {
  'id' : SubjectId,
  'topicCount' : bigint,
  'name' : SubjectName,
  'description' : string,
}
export type SubjectId = bigint;
export type SubjectName = { 'physiology' : null } |
  { 'anatomy' : null } |
  { 'biochemistry' : null };
export interface SubjectProgress {
  'topicsStudied' : bigint,
  'masteryPercent' : number,
  'totalStudyMinutes' : bigint,
  'quizzesTaken' : bigint,
  'subjectId' : SubjectId,
  'flashcardsReviewed' : bigint,
}
export type Timestamp = bigint;
export interface Topic {
  'id' : TopicId,
  'title' : string,
  'description' : string,
  'subjectId' : SubjectId,
  'orderIndex' : bigint,
}
export type TopicId = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProgress {
  'streakDays' : bigint,
  'lastStudyDate' : [] | [Timestamp],
  'totalStudyMinutes' : bigint,
  'subjectProgress' : Array<SubjectProgress>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createQuiz' : ActorMethod<[TopicId, bigint], Quiz>,
  'generateQuestionsForTopic' : ActorMethod<[TopicId], Array<Question>>,
  'getCase' : ActorMethod<[CaseId], [] | [EceCase]>,
  'getCases' : ActorMethod<[[] | [SubjectId]], Array<EceCase>>,
  'getDueFlashcards' : ActorMethod<[], Array<Flashcard>>,
  'getFlashcards' : ActorMethod<[TopicId], Array<Flashcard>>,
  'getQuestion' : ActorMethod<[QuestionId], [] | [Question]>,
  'getQuestions' : ActorMethod<[TopicId], Array<Question>>,
  'getQuizHistory' : ActorMethod<[], Array<QuizAttempt>>,
  'getQuizResult' : ActorMethod<[QuizId], [] | [QuizResult]>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTopic' : ActorMethod<[TopicId], [] | [Topic]>,
  'getTopics' : ActorMethod<[SubjectId], Array<Topic>>,
  'getUserProgress' : ActorMethod<[], UserProgress>,
  'markQuestionFlagged' : ActorMethod<[QuestionId], undefined>,
  'recordStudySession' : ActorMethod<[SubjectId, bigint], undefined>,
  'reviewFlashcard' : ActorMethod<[FlashcardId, ReviewRating], undefined>,
  'submitCaseAnswer' : ActorMethod<[CaseId, bigint, string], undefined>,
  'submitQuiz' : ActorMethod<[QuizId, Array<bigint>], QuizResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];