/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CaseQuestion {
    text: string;
    modelAnswer: string;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface EceCase {
    id: CaseId;
    title: string;
    subjectTags: Array<SubjectId>;
    difficulty: DifficultyLevel;
    learningPoints: Array<string>;
    questions: Array<CaseQuestion>;
    presentation: string;
}
export interface Quiz {
    id: QuizId;
    status: QuizStatus;
    createdAt: Timestamp;
    questionIds: Array<QuestionId>;
    topicId: TopicId;
}
export type QuestionId = bigint;
export interface QuizResult {
    completedAt: Timestamp;
    score: bigint;
    totalQuestions: bigint;
    correctAnswers: Array<boolean>;
    quizId: QuizId;
    percentage: number;
}
export interface SubjectProgress {
    topicsStudied: bigint;
    masteryPercent: number;
    totalStudyMinutes: bigint;
    quizzesTaken: bigint;
    subjectId: SubjectId;
    flashcardsReviewed: bigint;
}
export interface UserProgress {
    streakDays: bigint;
    lastStudyDate?: Timestamp;
    totalStudyMinutes: bigint;
    subjectProgress: Array<SubjectProgress>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type TopicId = bigint;
export type FlashcardId = bigint;
export type CaseId = bigint;
export interface QuizAttempt {
    completedAt: Timestamp;
    answers: Array<bigint>;
    score: bigint;
    totalQuestions: bigint;
    quizId: QuizId;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Flashcard {
    id: FlashcardId;
    front: string;
    back: string;
    topicId: TopicId;
}
export interface Topic {
    id: TopicId;
    title: string;
    description: string;
    subjectId: SubjectId;
    orderIndex: bigint;
}
export interface Question {
    id: QuestionId;
    source: Variant_manual_aiGenerated;
    correctIndex: bigint;
    explanation: string;
    text: string;
    options: Array<string>;
    isFlagged: boolean;
    topicId: TopicId;
}
export type SubjectId = bigint;
export interface Subject {
    id: SubjectId;
    topicCount: bigint;
    name: SubjectName;
    description: string;
}
export type QuizId = bigint;
export enum DifficultyLevel {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum QuizStatus {
    active = "active",
    completed = "completed"
}
export enum ReviewRating {
    easy = "easy",
    good = "good",
    hard = "hard"
}
export enum SubjectName {
    physiology = "physiology",
    anatomy = "anatomy",
    biochemistry = "biochemistry"
}
export enum Variant_manual_aiGenerated {
    manual = "manual",
    aiGenerated = "aiGenerated"
}
export interface backendInterface {
    createQuiz(topicId: TopicId, questionCount: bigint): Promise<Quiz>;
    generateQuestionsForTopic(topicId: TopicId): Promise<Array<Question>>;
    getCase(id: CaseId): Promise<EceCase | null>;
    getCases(subjectId: SubjectId | null): Promise<Array<EceCase>>;
    getDueFlashcards(): Promise<Array<Flashcard>>;
    getFlashcards(topicId: TopicId): Promise<Array<Flashcard>>;
    getQuestion(id: QuestionId): Promise<Question | null>;
    getQuestions(topicId: TopicId): Promise<Array<Question>>;
    getQuizHistory(): Promise<Array<QuizAttempt>>;
    getQuizResult(quizId: QuizId): Promise<QuizResult | null>;
    getSubjects(): Promise<Array<Subject>>;
    getTopic(id: TopicId): Promise<Topic | null>;
    getTopics(subjectId: SubjectId): Promise<Array<Topic>>;
    getUserProgress(): Promise<UserProgress>;
    markQuestionFlagged(questionId: QuestionId): Promise<void>;
    recordStudySession(subjectId: SubjectId, durationMinutes: bigint): Promise<void>;
    reviewFlashcard(cardId: FlashcardId, rating: ReviewRating): Promise<void>;
    submitCaseAnswer(caseId: CaseId, questionIndex: bigint, answer: string): Promise<void>;
    submitQuiz(quizId: QuizId, answers: Array<bigint>): Promise<QuizResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { CaseId as _CaseId, CaseQuestion as _CaseQuestion, DifficultyLevel as _DifficultyLevel, EceCase as _EceCase, Question as _Question, QuestionId as _QuestionId, Quiz as _Quiz, QuizId as _QuizId, QuizResult as _QuizResult, QuizStatus as _QuizStatus, ReviewRating as _ReviewRating, Subject as _Subject, SubjectId as _SubjectId, SubjectName as _SubjectName, SubjectProgress as _SubjectProgress, Timestamp as _Timestamp, Topic as _Topic, TopicId as _TopicId, UserProgress as _UserProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createQuiz(arg0: TopicId, arg1: bigint): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1);
                return from_candid_Quiz_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1);
            return from_candid_Quiz_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateQuestionsForTopic(arg0: TopicId): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQuestionsForTopic(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQuestionsForTopic(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCase(arg0: CaseId): Promise<EceCase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCases(arg0: SubjectId | null): Promise<Array<EceCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCases(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCases(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDueFlashcards(): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueFlashcards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueFlashcards();
            return result;
        }
    }
    async getFlashcards(arg0: TopicId): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashcards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashcards(arg0);
            return result;
        }
    }
    async getQuestion(arg0: QuestionId): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestion(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestion(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestions(arg0: TopicId): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizHistory(): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizHistory();
            return result;
        }
    }
    async getQuizResult(arg0: QuizId): Promise<QuizResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResult(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResult(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopic(arg0: TopicId): Promise<Topic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopic(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopic(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopics(arg0: SubjectId): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopics(arg0);
            return result;
        }
    }
    async getUserProgress(): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress();
                return from_candid_UserProgress_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress();
            return from_candid_UserProgress_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async markQuestionFlagged(arg0: QuestionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markQuestionFlagged(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markQuestionFlagged(arg0);
            return result;
        }
    }
    async recordStudySession(arg0: SubjectId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordStudySession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordStudySession(arg0, arg1);
            return result;
        }
    }
    async reviewFlashcard(arg0: FlashcardId, arg1: ReviewRating): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewFlashcard(arg0, to_candid_ReviewRating_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewFlashcard(arg0, to_candid_ReviewRating_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitCaseAnswer(arg0: CaseId, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCaseAnswer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCaseAnswer(arg0, arg1, arg2);
            return result;
        }
    }
    async submitQuiz(arg0: QuizId, arg1: Array<bigint>): Promise<QuizResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_DifficultyLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EceCase_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EceCase): EceCase {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_QuizStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizStatus): QuizStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Quiz_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quiz): Quiz {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectName_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectName): SubjectName {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProgress_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Question]): Question | null {
    return value.length === 0 ? null : from_candid_Question_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizResult]): QuizResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Topic]): Topic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EceCase]): EceCase | null {
    return value.length === 0 ? null : from_candid_EceCase_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CaseId;
    title: string;
    subjectTags: Array<_SubjectId>;
    difficulty: _DifficultyLevel;
    learningPoints: Array<string>;
    questions: Array<_CaseQuestion>;
    presentation: string;
}): {
    id: CaseId;
    title: string;
    subjectTags: Array<SubjectId>;
    difficulty: DifficultyLevel;
    learningPoints: Array<string>;
    questions: Array<CaseQuestion>;
    presentation: string;
} {
    return {
        id: value.id,
        title: value.title,
        subjectTags: value.subjectTags,
        difficulty: from_candid_DifficultyLevel_n12(_uploadFile, _downloadFile, value.difficulty),
        learningPoints: value.learningPoints,
        questions: value.questions,
        presentation: value.presentation
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuizId;
    status: _QuizStatus;
    createdAt: _Timestamp;
    questionIds: Array<_QuestionId>;
    topicId: _TopicId;
}): {
    id: QuizId;
    status: QuizStatus;
    createdAt: Timestamp;
    questionIds: Array<QuestionId>;
    topicId: TopicId;
} {
    return {
        id: value.id,
        status: from_candid_QuizStatus_n3(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        questionIds: value.questionIds,
        topicId: value.topicId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubjectId;
    topicCount: bigint;
    name: _SubjectName;
    description: string;
}): {
    id: SubjectId;
    topicCount: bigint;
    name: SubjectName;
    description: string;
} {
    return {
        id: value.id,
        topicCount: value.topicCount,
        name: from_candid_SubjectName_n21(_uploadFile, _downloadFile, value.name),
        description: value.description
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streakDays: bigint;
    lastStudyDate: [] | [_Timestamp];
    totalStudyMinutes: bigint;
    subjectProgress: Array<_SubjectProgress>;
}): {
    streakDays: bigint;
    lastStudyDate?: Timestamp;
    totalStudyMinutes: bigint;
    subjectProgress: Array<SubjectProgress>;
} {
    return {
        streakDays: value.streakDays,
        lastStudyDate: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.lastStudyDate)),
        totalStudyMinutes: value.totalStudyMinutes,
        subjectProgress: value.subjectProgress
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    source: {
        manual: null;
    } | {
        aiGenerated: null;
    };
    correctIndex: bigint;
    explanation: string;
    text: string;
    options: Array<string>;
    isFlagged: boolean;
    topicId: _TopicId;
}): {
    id: QuestionId;
    source: Variant_manual_aiGenerated;
    correctIndex: bigint;
    explanation: string;
    text: string;
    options: Array<string>;
    isFlagged: boolean;
    topicId: TopicId;
} {
    return {
        id: value.id,
        source: from_candid_variant_n8(_uploadFile, _downloadFile, value.source),
        correctIndex: value.correctIndex,
        explanation: value.explanation,
        text: value.text,
        options: value.options,
        isFlagged: value.isFlagged,
        topicId: value.topicId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): DifficultyLevel {
    return "easy" in value ? DifficultyLevel.easy : "hard" in value ? DifficultyLevel.hard : "medium" in value ? DifficultyLevel.medium : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    physiology: null;
} | {
    anatomy: null;
} | {
    biochemistry: null;
}): SubjectName {
    return "physiology" in value ? SubjectName.physiology : "anatomy" in value ? SubjectName.anatomy : "biochemistry" in value ? SubjectName.biochemistry : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): QuizStatus {
    return "active" in value ? QuizStatus.active : "completed" in value ? QuizStatus.completed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manual: null;
} | {
    aiGenerated: null;
}): Variant_manual_aiGenerated {
    return "manual" in value ? Variant_manual_aiGenerated.manual : "aiGenerated" in value ? Variant_manual_aiGenerated.aiGenerated : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EceCase>): Array<EceCase> {
    return value.map((x)=>from_candid_EceCase_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subject>): Array<Subject> {
    return value.map((x)=>from_candid_Subject_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ReviewRating_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewRating): _ReviewRating {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectId | null): [] | [_SubjectId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewRating): {
    easy: null;
} | {
    good: null;
} | {
    hard: null;
} {
    return value == ReviewRating.easy ? {
        easy: null
    } : value == ReviewRating.good ? {
        good: null
    } : value == ReviewRating.hard ? {
        hard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
